title: Martin Jørgensen
tagline: Machine Learning Researcher
description: Machine Learning Postdoctoral Researcher at University of Oxford 
url: jorgensenmart.github.io
theme: jekyll-theme-tactile
plugins:
  - jekyll-seo-tag

twitter:
  username: JorgensenMart
  card: summary
