title: Martin Jørgensen
site.tagline: Machine Learning Researcher at University of Oxford
description: Machine Learning Researcher
url: jorgensenmart.github.io
theme: jekyll-theme-tactile
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

twitter:
  username: JorgensenMart
  card: summary
