title: Martin Jørgensen
description: Machine Learning Researcher
url: jorgensenmart.github.io
theme: jekyll-theme-tactile
plugins:
  - jekyll-seo-tag

twitter:
  username: JorgensenMart
  card: summary
