title: Martin Jørgensen
page.title: Machine Learning Researcher
description: Personal webpage for, researcher at Oxford University, Martin Jorgensen. 
url: jorgensenmart.github.io
theme: jekyll-theme-tactile
plugins:
  - jekyll-seo-tag

twitter:
  username: JorgensenMart
  card: summary
